apiVersion: apps/v1
kind: Deployment
metadata:
  name: napp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: napp
  template:
    metadata:
      labels:
        app: napp
    spec:
      containers:
      - name: napp
        image: fra.ocir.io/frbclquc7alv/node-js/new-repo-lab:latest
        imagePullPolicy: Always
        ports:
        - name: napp
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: napp-lb
  labels:
    app: napp
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: napp

